name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: joeyx22lm/static-http-server-prometheus/static-http-server-prometheus
          tag_with_ref: true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
